LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/tracks2_9M.csv' INTO TABLE blasta.tracks CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (tid, aid, username, title, likes, comments, plays, genre, last_modified, `date`);

LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/likes.csv' INTO TABLE likes CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (uid, tid, aid, `date`);

LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/tags1M.csv' INTO TABLE tags CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (tid, aid, tag);

LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/starttracks9533.csv' INTO TABLE start_tracks CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (tid, `date`);

LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/fans1m.csv' INTO TABLE fans CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (tid,uid, `date`);


LOAD DATA LOCAL INFILE '/Users/Johannes/Dropbox/DSR/portfolioproject/bigblastadump/echo250.csv' INTO TABLE echonest CHARACTER SET UTF8 FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' (`tid`,`aid`,`eid`, `danceability` , `acousticness` , `energy`, `duration`, `instrumentalness` , `key` , `liveness` , `mode` , `speechiness` , `tempo` , `valence` , `loudness` , `loudness_max_mean` , `loudness_max_std` , `loudness_max_kurt` , `loudness_max_skew` , `pitches01_mean` , `pitches01_std` , `pitches01_kurt` , `pitches01_skew` , `pitches02_mean` , `pitches02_std` , `pitches02_kurt` , `pitches02_skew` , `pitches03_mean` , `pitches03_std` , `pitches03_kurt` , `pitches03_skew` , `pitches04_mean` , `pitches04_std` , `pitches04_kurt` , `pitches04_skew` , `pitches05_mean` , `pitches05_std` , `pitches05_kurt` , `pitches05_skew` , `pitches06_mean` , `pitches06_std` , `pitches06_kurt` , `pitches06_skew` , `pitches07_mean` , `pitches07_std` , `pitches07_kurt` , `pitches07_skew` , `pitches08_mean` , `pitches08_std` , `pitches08_kurt` , `pitches08_skew` , `pitches09_mean` , `pitches09_std` , `pitches09_kurt` , `pitches09_skew` , `pitches10_mean` , `pitches10_std` , `pitches10_kurt` , `pitches10_skew` , `pitches11_mean` , `pitches11_std` , `pitches11_kurt` , `pitches11_skew` , `pitches12_mean` , `pitches12_std` , `pitches12_kurt` , `pitches12_skew` , `timbre01_mean` , `timbre01_std` , `timbre01_kurt` , `timbre01_skew` , `timbre02_mean` , `timbre02_std` , `timbre02_kurt` , `timbre02_skew` , `timbre03_mean` , `timbre03_std` , `timbre03_kurt` , `timbre03_skew` , `timbre04_mean` , `timbre04_std` , `timbre04_kurt` , `timbre04_skew` , `timbre05_mean` , `timbre05_std` , `timbre05_kurt` , `timbre05_skew` , `timbre06_mean` , `timbre06_std` , `timbre06_kurt` , `timbre06_skew` , `timbre07_mean` , `timbre07_std` , `timbre07_kurt` , `timbre07_skew` , `timbre08_mean` , `timbre08_std` , `timbre08_kurt` , `timbre08_skew` , `timbre09_mean` , `timbre09_std` , `timbre09_kurt` , `timbre09_skew` , `timbre10_mean` , `timbre10_std` , `timbre10_kurt` , `timbre10_skew` , `timbre11_mean` , `timbre11_std` , `timbre11_kurt` , `timbre11_skew` , `timbre12_mean` , `timbre12_std` , `timbre12_kurt` , `timbre12_skew` , `date` );



